### ISSUE TITLE
can-import can-tag fails silently when tag does not exist - P(4) ~5

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-view-import#2]
From: https://github.com/canjs/canjs/issues/1859

```
<can-import from="app/component/" can-tag="app-loading">
          <app-component></app-component>
</can-import>
```

If app-loading is not already imported, can-import will fail without throwing an error. It never renders app-component.

**Comment by Macrofig** [comment]
Found the unique use cases that cause this behavior

In all these use cases, the desired tag has not been previously registered with `can-view-callbacks` (specifically using [this signature](https://canjs.com/doc/can-view-callbacks.tag.html#callbacks_tag_tagName_tagHandler_el_tagData__))

## Special Characters

```
<can-import from="app/component/" can-tag="app-loading">
          <app-component></app-component>
</can-import>
```

No error is thrown and  `app-component` never renders.

### Solution

- Log an error using `can-util`.dev when attempting to load a tag that has not been registered.
- Render the content of can-import when promise is resolved

## No Special Characters

> can-component allows this but logs a warning.

```
<can-import from="app/component/" can-tag="loading">
          <app-component></app-component>
</can-import>
```

An error is thrown because `can-view-callbacks`.tag returns undefined and `can-view-import` expects a function.  Also, `app-component` never renders.

### Solution

- Log an error using `can-util`.dev when attempting to load a tag that has not been registered.
- Render the content of can-import when promise is resolved

## Actual Implementation

- Check if tag exists or is valid
- If not valid/not exists, log warning
- It not valid/not exists, render content of can-import as if `can-tag` property did not exist.

The warning logs were resolved yesterday. Checking today how difficult it will be to render content when `cat-tag` value is invalid.

**Comment by phillipskevin** [comment]
closed by https://github.com/canjs/can-view-import/pull/57.
